[build-system]
requires = [
    "setuptools>=63",
    "wheel>=0.36.2",
    "pybind11>=2.9.2",
]

build-backend = "setuptools.build_meta"

# See: https://cibuildwheel.readthedocs.io/en/stable/options/#examples
[tool.cibuildwheel.linux]
before-all = "yum install -y libsndfile libX11-devel libXrandr-devel libXinerama-devel libXrender-devel libXcomposite-devel libXinerama-devel libXcursor-devel freetype-devel"

[[tool.cibuildwheel.overrides]]
# Use apk instead of yum when building on Alpine Linux
select = "*-musllinux*"
before-all = "apk add libsndfile libX11-dev libXrandr-dev libXinerama-dev libXrender-dev libXcomposite-dev libXinerama-dev libXcursor-dev freetype-dev"
